### ISSUE TITLE
Missing Dependency certifi

### ISSUE THREAD

**Issue by q-nk** [Nitrokey/nethsm-sdk-py#33]
After installing the nethsm module with

`pip install nethsm`

it cannot be imported, because the dependency to certifi is missing.
It has to be installed manually, to import the nethsm module.

`pip install certifi`

**Comment by robin-nitrokey** [comment]
Thanks for the report.  Probably one of our dev dependencies installs `certifi` so we did not see this during testing and in the CI.  So this means there are two tasks:
- [ ] add `certify` dependency
- [ ] add test without dev dependencies to the CI

**Comment by robin-nitrokey** [comment]
Checking this in the CI is a bit harder than expected:  `flit` depends on `certifi`, so we cannot use `flit install`.  When using `pip install`, which only depends on `flit_core`, we run into this issue:  https://github.com/pypa/flit/issues/386.  Basically, as `flit` does not find a static `__version__` value in `__init__.py`, it tries to load the module to check the computed version.  Workarounds:
- remove the `VERSION` file and set `__version__` directly
- modify `__init__.py` in the CI using the contents of `VERSION` before running the installation check

**Comment by q-nk** [comment]
Did I understand correctly that the version has to be hard coded in __init__.py?

_it tries to load the module to check the computed version (which does not work)._

Why exactly is it no possible to fill the variable `__version__` by code that is executed when the module is loaded? 
E.g., something like

```
def get_version():
  with open("VERSION", r) as fd:
    version = fd.read()
    #do some checks
    return version

__version__ = get_version()    
```

If I understand you correctly, you tried this? 
I mean it would be more beautiful, as the same data is not stored in two places.
It would also avoid the, in my opinion rather extensive version determination in https://github.com/Nitrokey/nethsm-sdk-py/pull/47/commits/aaf81badd60df21a19042253a79431be3552682e#diff-f95d5c25ce613cd9c56121fda16cda61e200c9e9bbb68a3ac410b27dfdde447c

Further is the VERSION file no longer needed an can now be deleted, right?
