### ISSUE TITLE
Parse timestamps, IP addresses, etc.

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nethsm-sdk-py#46]
Some commands return data like timestamps or IP addresses.  Currently, we just return them as strings, but it would make sense to parse them into the corresponding types from the Python standard library.

**Comment by spacether** [comment]
There are some utilities avilable for this in the client. See as_datetime, as_date, as_decimal, as_uuid here: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/client/petstore/python/src/petstore_api/schemas/format.py#L85

**Comment by robin-nitrokey** [comment]
Implemented for datetime in https://github.com/Nitrokey/nethsm-sdk-py/pull/95.

**Comment by robin-nitrokey** [comment]
Not sure if it is worth the effort for other types.  Let’s close it for now and potentially revisit it in the future.
